### ISSUE TITLE
The default "sleep" payloads argument (6) is too short, causing loads of false positives

### ISSUE THREAD

**Issue by ewilded** [modzero/mod0BurpUploadScanner#10]
It would be great to have the ability to manually set the delay used for the "sleep" command injection payloads to avoid false positives in environments whereas the standard responses are a bit lengthy. Also, would be nice to actually check the standard response time first and then calculate the delta to establish the eventual execution indicator delay. Currently getting false positives with the hardcoded 6-second delay while the app takes between 3 to 15 seconds to respond to the upload request, without any correlation with the payload. Could avoid this if I were able to set the delay to like 20 seconds, which would be the minimum response time to raise an issue.

**Comment by floyd-fuh** [comment]
Agree. For now simply change SLEEP_TIME = 6 in the BurpExtender class.

**Comment by floyd-fuh** [comment]
Configurable sleep time will be available as a feature in BApp after an update as soon as the pull request was accepted by Portswigger.

Although measuring default response time would be an option, it is also not fool prove as when the response times will just get longer later on (e.g. because of network issues), it might still create false positives. Also I do not want to send any requests to the target before the button for a scan is clicked, but it wouldn't be possible to show a "measured sane default value" in the UI before sending a request. Kind of a chicken-egg problem. The configurable UI option has to be enough for now.
