### ISSUE TITLE
Marker across multiple lines

### ISSUE THREAD

**Issue by luh2** [modzero/mod0BurpUploadScanner#13]
Hi,

I've got a case, where the uploaded file will get an ID that needs to be used for getting it afterwards.

```
<td class="textdata">
  <a href="attachment.do?reportId=1588&amp;attachmentId=852&amp;action=1">
	DwldzhALBfRceiptckeywordsJSP3fHP.jsp.pdf
  </a>
</td>
```

What needs to be parsed is the attachmentId. Getting that in a single upload is easy.
But since multiple files can be uploaded and the order of display is a bit random, it would be very helpful to be able set a marker that can contain newlines.

The following is a related but not really the same issue. If you want me to put this into a separate issue, let me know, and I'll put it there. 

In the same case, it would be really nice to use `${FILENAME}` already in the marker, like when building the URL. For obvious reasons if you see the response above :)

**Comment by floyd-fuh** [comment]
Hehe, I was waiting for this feature request :)

So using ${FILENAME} in the marker should be no problem and I will implement that.

Doing something that contains newlines is a little bit more tricky, because obviously you can not type a newline in a Java Swing UI element. So I'll probably implement something like 
`${PYTHONSTR:'Here you could specify a string that is usually printed by the Python repr function, such as \n (that would be a newline now)'}` which would then be supported in every UI element. Sounds good?

**Comment by luh2** [comment]
Perfect!

**Comment by floyd-fuh** [comment]
This is now available exactly with the `${PYTHONSTR:'foo\nbar'}` syntax explained above. See README:
https://github.com/modzero/mod0BurpUploadScanner/blob/master/README.md#1-start-marker-to-parse-url-from-response

Will take a while until it lands in the BApp store
