### ISSUE TITLE
Request 1 not showing the testing payload

### ISSUE THREAD

**Issue by Hipapheralkus** [modzero/mod0BurpUploadScanner#15]
I've noticed that when Issue is generated, the Request 1 is always identical to the one sent into the Upload Scanner in the first place. 

Would it be possible to instead have the actual request with the particular payload used? Which would be identical to the one on the Done uploads, but as there are usually hundreds and no search, it gets tricky to find something...

**Comment by floyd-fuh** [comment]
I know, this is a design decision. This is actually a limitation I implemented because I don't want to keep every request/response done by the Upload Scanner in memory. You can imagine I would have to keep all requests/responses that do not result in an issue in memory forever, which is in practice all requests :).

Additionally, I try to minimize the memory footprint by putting DownloadMatchers in a set rather than a list. So there is no 1:1 mapping (several uploads might have the same DownloadMatcher associated).

Or in other words as stated in the code of the extension:

```
class DownloadMatcherCollection(object):
    # TODO feature: Due to memory consumption we do not add any upload/preflight requests to the issue as we need to keep them in
    # memory forever. We hope the original brr is kept as a reference rather than a copy in memory so not using
    # too much memory. However, the upload request for each file would be a lot different and would use a lot more
    # memory. I think this is a sane choice, but I haven't tested it.
    # Another problem there: We try to keep the amount of DownloadMatcher as small as possible by putting
    # them in a set and removing duplicates. Therefore several upload requests associate with *one* DownloadMatcher
    # therefore we can not simply match a DownloadMatcher to one upload request...
    # Maybe we can simply work with self._callbacks.saveBuffersToTempFiles some more ???
```

I've quickly discussed this with the Portswigger guys and they seem to recreate how the request must have looked like from the payload in their scanner checks. However, that's not a good option either in my case, as the "payload" would be file contents, which is again a lot of data we don't want to keep in memory forever.

So short answer: No, I'm sorry, you will have to run the scan again and activate Logger++ or the Done Uploads tab. Alternatively, you can check the source code of the Upload Scanner, which will usually tell you how the upload request was generated.

Did you find something interesting on a website?
