### ISSUE TITLE
UploadScanner bug

### ISSUE THREAD

**Issue by Rockcena** [modzero/mod0BurpUploadScanner#17]
```
Traceback (most recent call last):
  File "/Users/apple/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 813, in processHttpMessage
    url = FloydsHelpers.u2s(iRequestInfo.getUrl().toString())
AttributeError: 'NoneType' object has no attribute 'toString'

Upload Scanner Version: 1.0.3

Jython version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
Java version: 1.8.0_112
```

**Comment by Rockcena** [comment]
Issue #12

**Comment by floyd-fuh** [comment]
See commit https://github.com/modzero/mod0BurpUploadScanner/commit/2f59f200c958bf56ff7b1a1973c25d6b985725df and https://github.com/modzero/mod0BurpUploadScanner/commit/f27e7237bd14e9bc3cd98ada05d57aebebda809d

Although I don't know why a request can have no URL, this is fixed with the next update.

Thanks for reporting!

**Comment by floyd-fuh** [comment]
Will be fixed when https://github.com/PortSwigger/upload-scanner/pull/6 is merged
