### ISSUE TITLE
flexinjector configured but file content not found in upload request

### ISSUE THREAD

**Issue by dorkerdevil** [modzero/mod0BurpUploadScanner#33]
I was testing a site profile, so i select a .png file and then sended the request to uploadscanner
and set everything but i m getting this error

"flexinjector configured but file content not found in upload request, rare case of javascript changes? aborting

here is how request look like

POST /api/content HTTP/1.1
Host: example.com
User-Agent: Firefox/62.0
Accept: application/vnd.zinc+json;level=17
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: image/png
Authorization: Basic 
Timestamp: 2018-11-29T20:34:56.551+05:30
X-Requested-With: XMLHttpRequest
Content-Length: 77643
Cookie: some cookies here ..
Connection: close

‰PNG
...<snipt>

**Comment by floyd-fuh** [comment]
You need to check if the PNG bytes are 1:1 the same as the PNG bytes in the file you specified in the flexiinjector. If not, that's the problem.

One way to work around this is to take the PNG bytes in the HTTP request you see, store them 1:1 in a file on the disc, then specify that file in Flexiinjector.

This is not an issue with the upload scanner, it told you exactly what the problem is: "flexinjector configured but file content not found in upload request, rare case of javascript changes?"

**Comment by dorkerdevil** [comment]
thanks for explaination
